--------------------------------------------------------------------------------
-- Tabela: DATA_JOBS
-- Estrutura oficial com base no dataset Data Science Job Salaries
--------------------------------------------------------------------------------

CREATE TABLE DATA_JOBS (
    
    ------------------------------------------------------------------------
    -- Identificador único (Primary Key)
    ------------------------------------------------------------------------
    id_job INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_data_jobs PRIMARY KEY,

    ------------------------------------------------------------------------
    -- Ano em que o salário foi pago
    ------------------------------------------------------------------------
    work_year INTEGER NOT NULL,
        -- Example: 2023

    ------------------------------------------------------------------------
    -- Nível de experiência (EN, MI, SE, EX)
    ------------------------------------------------------------------------
    experience_level VARCHAR2(5) NOT NULL,
        -- EN: Entry-level / Junior
        -- MI: Mid-level / Intermediate
        -- SE: Senior-level / Expert
        -- EX: Executive-level / Director

    ------------------------------------------------------------------------
    -- Tipo de emprego (PT, FT, CT, FL)
    ------------------------------------------------------------------------
    employment_type VARCHAR2(5) NOT NULL,
        -- PT: Part-time
        -- FT: Full-time
        -- CT: Contract
        -- FL: Freelance

    ------------------------------------------------------------------------
    -- Título do cargo
    ------------------------------------------------------------------------
    job_title VARCHAR2(120) NOT NULL,
        -- Example: Data Scientist, ML Engineer

    ------------------------------------------------------------------------
    -- Valor do salário bruto (moeda original)
    ------------------------------------------------------------------------
    salary NUMBER(12,2) NOT NULL,
        -- Total gross salary

    ------------------------------------------------------------------------
    -- Moeda do salário (ISO 4217)
    ------------------------------------------------------------------------
    salary_currency VARCHAR2(5) NOT NULL,
        -- Examples: USD, EUR, GBP, BRL

    ------------------------------------------------------------------------
    -- Salário convertido para USD
    ------------------------------------------------------------------------
    salary_in_usd NUMBER(12,2) NOT NULL,
        -- FX ajustado usando taxa média anual

    ------------------------------------------------------------------------
    -- País de residência do funcionário (ISO 3166-1 alpha-2)
    ------------------------------------------------------------------------
    employee_residence VARCHAR2(5) NOT NULL,
        -- Example: US, BR, DE

    ------------------------------------------------------------------------
    -- Grau de trabalho remoto (0, 50, 100)
    ------------------------------------------------------------------------
    remote_ratio INTEGER NOT NULL,
        -- 0   = On-site (<20%)
        -- 50  = Parcialmente remoto
        -- 100 = Totalmente remoto (>80%)

    ------------------------------------------------------------------------
    -- País da empresa (ISO 3166-1 alpha-2)
    ------------------------------------------------------------------------
    company_location VARCHAR2(5) NOT NULL,
        -- País da sede ou filial contratante

    ------------------------------------------------------------------------
    -- Tamanho da empresa (S, M, L)
    ------------------------------------------------------------------------
    company_size VARCHAR2(2) NOT NULL
        -- S: < 50 funcionários
        -- M: 50-250 funcionários
        -- L: > 250 funcionários
);

-- DROP TABLE DATA_JOBS PURGE;

--------------------------------------------------------------------------------
-- Tabela auxiliar COMPANY_INFO
-- Armazena informações sobre empresas da área de tecnologia.
--------------------------------------------------------------------------------

CREATE TABLE COMPANY_INFO (
    company_location VARCHAR2(5) PRIMARY KEY,
        -- Código ISO do país, ex.: US, BR, DE

    company_size VARCHAR2(2) NOT NULL,
        -- S, M, L (small, medium, large)

    industry VARCHAR2(100) NOT NULL
        -- Setor da empresa (Technology, AI, Cloud Services, etc.)
);

-- DROP TABLE COMPANY_INFO PURGE;